version: '3.9'
services:
  bot-telegram:
    build: .
    volumes:
      - ./.env:/app/.env
      - ./aiogram-bot:/app

    networks:
      - battery_battery-net
networks:
  battery_battery-net:
    external: true