version: '3.9'
services:
  bot-telegram:
    image: fedxl/storage:battery-bot
    command: python run_bot.py
    volumes:
      - ./.env:/app/.env
    networks:
      - battery_battery-net
networks:
  battery_battery-net:
    external: true