FROM python:3.12-alpine3.21
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
COPY req.txt .
RUN pip install --no-cache-dir -r req.txt
# Даем права на выполнение для restart.sh

COPY ./aiogram-bot /app
RUN chmod +x /app/restart.sh